package edu.javacourse.register.pacakge;

import edu.javacourse.register.domain.Person;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;

import java.util.List;

/***
 * That class manipulate data from person table located in register_office DB
 */
public class PersonManager {

    public static void main(String[] args) {
        SessionFactory sessionFactory = buildSessionFactory();

        System.out.println();
        System.out.println();
        System.out.println();

        Session session = sessionFactory.openSession();

        //Start transaction to modify data from register_office DB
        session.getTransaction().begin();

        Person person = new Person();
        person.setFirstName("Василий");
        person.setLastName("Сидоров");

        //Save Person entity in register_office DB without Id using INSERT (Id will be autogenerated).
        //return Serializable id describe result of saving Person entity into table from register_office DB
        Long id = (Long) session.save(person);
        System.out.println(id);

        session.getTransaction().commit();
        session.close();

        //Get added person with "id" identificator from "person" table of city_register DB
        session = sessionFactory.openSession();
        Person personFromDB = session.get(Person.class, id);
        System.out.println(personFromDB);
        session.close();

        session = sessionFactory.openSession();
        List<Person> list = session.createQuery("FROM Person", Person.class).list();
        list.forEach(System.out::println);
        session.close();
    }

    private static SessionFactory buildSessionFactory() {
        try {
            StandardServiceRegistry serviceRegistry = new StandardServiceRegistryBuilder()
                    .configure("hibernate.cfg.xml").build();

            Metadata metadata = new MetadataSources(serviceRegistry).getMetadataBuilder().build();

            return metadata.getSessionFactoryBuilder().build();
        } catch (Throwable ex) {

            System.err.println("Initial SessionFactory creation failed." + ex);
            throw new ExceptionInInitializerError(ex);
        }
    }
}
